//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myimage.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class bilingaddress
    {
        public int bilid { get; set; }
        [Required(ErrorMessage = "Enter First Name")]
       
        public string Fname { get; set; }
        [Required(ErrorMessage = "Enter Last Name")]
        public string Lname { get; set; }
        [Required(ErrorMessage = "Enter Address")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Enter Contact Number")]
        public string ContactNumb { get; set; }
        [Required(ErrorMessage = "Enter State")]
        public string State { get; set; }
        [Required(ErrorMessage = "Enter Postal Code")]
        public int PostalCode { get; set; }
    }
}
