//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myimage.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class myimagedatabaseEntities : DbContext
    {
        public myimagedatabaseEntities()
            : base("name=myimagedatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<registrationform> registrationforms { get; set; }
        public virtual DbSet<signin> signins { get; set; }
        public virtual DbSet<adminsignin> adminsignins { get; set; }
        public virtual DbSet<contactform> contactforms { get; set; }
        public virtual DbSet<sizeprize> sizeprizes { get; set; }
        public virtual DbSet<bilingaddress> bilingaddresses { get; set; }
        public virtual DbSet<paymentdetail> paymentdetails { get; set; }
        public virtual DbSet<image> images { get; set; }
        public virtual DbSet<userproduct> userproducts { get; set; }
    }
}
