//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myimage.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class paymentdetail
    {
        public int pyid { get; set; }
        [Required(ErrorMessage = "Enter Card Number")]
        public string Cardnumber { get; set; }
        [Required(ErrorMessage = "Enter EXP Date")]
        public int expdate { get; set; }
        [Required(ErrorMessage = "Enter CVC Code")]
        public int cvcode { get; set; }
        [Required(ErrorMessage = "Enter Card Owner Name")]
        public string cardowner { get; set; }
    }
}
