//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myimage.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class registrationform
    {
        public int regid { get; set; }
        [Required(ErrorMessage = "Enter First Name")]
        public string fname { get; set; }
        [Required(ErrorMessage = "Enter Last Name")]
        public string lname { get; set; }
        [Required(ErrorMessage = "Enter DOB")]
        public string dob { get; set; }
        [Required(ErrorMessage = "Enter Gender")]
        public string gender { get; set; }
        [Required(ErrorMessage = "Enter Phone Number")]
        public string phonenum { get; set; }
        [Required(ErrorMessage = "Enter Address")]
        public string address { get; set; }
        [Required(ErrorMessage = "Enter Email")]
        public string email { get; set; }
        [Required(ErrorMessage = "Enter Password")]
        [DataType(DataType.Password)]
        public string password { get; set; }
    
        public virtual signin signin { get; set; }
    }
}
