//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myimage.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class signin
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Enter Email")]
        
        public string email { get; set; }
        [Required(ErrorMessage = "Enter Password")]
        [DataType(DataType.Password)]
        public string password { get; set; }
    
        public virtual signin signin1 { get; set; }
        public virtual signin signin2 { get; set; }
        public virtual registrationform registrationform { get; set; }
    }
}
